FROM maven:3.6.3-openjdk-8

WORKDIR /

COPY settings.xml /usr/share/maven/conf/settings.xml
COPY online_album_by_springboot online_album_by_springboot
COPY package.sh package.sh

RUN chmod 744 package.sh

CMD ["/package.sh"]

