#!/bin/bash

DB_USERNAME=$1
DB_PASSWORD=$2
DB_HOST=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' online_album_db_1)
DB_PORT=$3
DB_IN_USE=$4
REDIS_HOST=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' online_album_redis_1)

sed -i "s/{db_username}/${DB_USERNAME}/g" application.yml
sed -i "s/{db_password}/${DB_PASSWORD}/g" application.yml
sed -i "s/{db_host}/${DB_HOST}/g" application.yml
sed -i "s/{db_port}/${DB_PORT}/g" application.yml
sed -i "s/{db_in_use}/${DB_IN_USE}/g" application.yml
sed -i "s/{redis_host}/${REDIS_HOST}/g" application.yml

